# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4c38736286fc308a62d116a8086df512626de42eeef653a4e411de8b78612471baae2db0bced1fd1e77dff02dc8a0ffbe761c268b6e59c1be578f1658c41524

test:
  secret_key_base: 28a1c3b0f57c650e3120bc937917980c1df944d95517a82481d6955b40242116655efc9544235fec65c032b4716cf7a66c738789487910b186b0707f839b17e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
